version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "5050:5050"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nginx/nginx.tmpl:/app/nginx.tmpl
      - ./nginx/proxy_vhost.conf:/etc/nginx/vhost.d/default
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=cloud9.localhost
      - HTTPS_METHOD=redirect

  nginx:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./app:/var/www/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
     - VIRTUAL_HOST=cloud9.localhost
    links:
      - fpm

  fpm:
    #image: php:fpm
    #build: ./templates/php
    image: localcloud9/php
    user: www-data
    environment:
      VOLUME_DIR: /home/myself/Projets Playground/localcloud9/volumes
      DOMAIN: cloud9.localhost
      CONTAINER_PREFIX: localcloud9_
      DOMAIN_PREFIX: ~
    volumes:
      - ./volumes/db:/var/db
      - ./app:/var/www/app:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: nginx-proxy